---
# Disk preparation tasks

- name: Check if VM disk already exists
  ansible.builtin.stat:
    path: "{{ vm_disk_path }}"
  register: vm_disk

- name: Create VM disk from golden image using backing file
  ansible.builtin.command:
    cmd: >
      qemu-img create -f qcow2
      -F qcow2
      -b {{ vm_template_dir }}/{{ vm_image_name }}
      {{ vm_disk_path }}
  when: not vm_disk.stat.exists
  changed_when: true

- name: Set permissions of VM disk
  ansible.builtin.file:
    path: "{{ vm_disk_path }}"
    mode: '0600'
